### ISSUE TITLE
As a user I want to be able to enter code into a graphical interface

### ISSUE THREAD

**Issue by aliveSurfin** [aliveSurfin/code_quality#19]
- [x] Syntax Highlighting with prism 
- [x] Code Entry
- [x]  User Testing

- [x] Ctrl S to force re analysis 
- [ ] Ctrl E to export
